# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

  
def test_testsearchingaproduct(driver):
    driver.get("https://automationexercise.com/")
    driver.find_element(By.LINK_TEXT, " Products").click()
    driver.find_element(By.ID, "search_product").click()
    driver.find_element(By.ID, "search_product").send_keys("GRAPHIC DESIGN MEN T SHIRT - BLUE")
    driver.find_element(By.ID, "submit_search").click()

    elementFound = driver.find_element(By.CSS_SELECTOR, "body > section:nth-child(3) > div > div > div.col-sm-9.padding-right > div > div.col-sm-4 > div > div.single-products > div.productinfo.text-center > p")

    assert elementFound.text == "GRAPHIC DESIGN MEN T SHIRT - BLUE"