# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

def test_testaddproducttocartsaucedemosite(driver):
    driver.get("https://www.saucedemo.com/")
    userName = "standard_user"
    password = "secret_sauce"

    driver.find_element(By.CSS_SELECTOR, "#user-name").send_keys(userName)
    driver.implicitly_wait(5)
    driver.find_element(By.CSS_SELECTOR, "#password").send_keys(password)
    driver.implicitly_wait(10)
    driver.find_element(By.CSS_SELECTOR, "#login-button").click()
    driver.implicitly_wait(10)
    driver.find_element(By.CSS_SELECTOR, "#add-to-cart-sauce-labs-backpack").click()
    driver.find_element(By.CSS_SELECTOR, "#add-to-cart-test\.allthethings\(\)-t-shirt-\(red\)").click()
    time.sleep(10)
    driver.find_element(By.CSS_SELECTOR, "#shopping_cart_container").click()
    driver.implicitly_wait(10)
    elmentCounter = driver.find_element(By.CSS_SELECTOR, "#shopping_cart_container > a > span").text

    assert elmentCounter == "2"


def test_testcheckoutordersaucedemo(driver) :
    self.driver.get("https://www.saucedemo.com/")
    userName = "standard_user"
    password = "secret_sauce"

    driver.find_element(By.CSS_SELECTOR,"#user-name").send_keys(userName)
    driver.implicitly_wait(5)
    driver.find_element(By.CSS_SELECTOR,"#password").send_keys(password)
    driver.implicitly_wait(10)
    driver.find_element(By.CSS_SELECTOR,"#login-button").click()
    driver.implicitly_wait(10)
    driver.find_element(By.CSS_SELECTOR,"#add-to-cart-sauce-labs-backpack").click()
    driver.find_element(By.CSS_SELECTOR,"#add-to-cart-test\.allthethings\(\)-t-shirt-\(red\)").click()
    time.sleep(10)
    driver.find_element(By.CSS_SELECTOR,"#shopping_cart_container").click()
    driver.implicitly_wait(10)
