# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import random
import string

def test_testsignup(driver):
    driver.get("https://automationexercise.com/")

    driver.find_element(By.LINK_TEXT, "Signup / Login").click()

    driver.find_element(By.NAME, "name").click()
    driver.find_element(By.NAME, "name").send_keys("Khaled blb")
    driver.implicitly_wait(5)

    driver.find_element(By.CSS_SELECTOR, ".signup-form input:nth-child(3)").send_keys(random_char(7)+"@gmaill.com")

    driver.implicitly_wait(5)

    driver.find_element(By.CSS_SELECTOR, ".signup-form input:nth-child(3)").send_keys(Keys.ENTER)
    driver.implicitly_wait(20)
    driver.find_element(By.ID, "id_gender1").click()
    driver.find_element(By.ID, "password").click()
    driver.find_element(By.ID, "password").send_keys("khaledd1")
    driver.find_element(By.ID, "days").click()
    dropdown = driver.find_element(By.ID, "days")
    dropdown.find_element(By.XPATH, "//option[. = '11']").click()
    driver.find_element(By.ID, "months").click()
    dropdown = driver.find_element(By.ID, "months")
    dropdown.find_element(By.XPATH, "//option[. = 'April']").click()
    driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(6)").click()
    driver.implicitly_wait(5)

    driver.find_element(By.ID, "years").click()
    dropdown = driver.find_element(By.ID, "years")
    dropdown.find_element(By.XPATH, "//option[. = '2013']").click()
    driver.find_element(By.CSS_SELECTOR, "body").click()
    driver.find_element(By.CSS_SELECTOR, "body").click()
    driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(22)").click()
    driver.find_element(By.ID, "first_name").click()
    driver.find_element(By.ID, "first_name").send_keys("Khaled")
    driver.find_element(By.ID, "name").send_keys("Khaled Blbesie")
    driver.find_element(By.ID, "last_name").send_keys("Blbesie")
    driver.find_element(By.ID, "address1").send_keys("7054")
    driver.find_element(By.ID, "address2").send_keys("9107001")
    dropdown = driver.find_element(By.ID, "country")
    dropdown.find_element(By.XPATH, "//option[. = 'Israel']").click()
    driver.find_element(By.ID, "state").send_keys("Israel")
    driver.find_element(By.ID, "city").send_keys("Jerusalem")
    driver.find_element(By.ID, "zipcode").send_keys("7054")
    driver.find_element(By.ID, "mobile_number").send_keys("+972544249695")
    driver.find_element(By.ID, "company").click()
    driver.implicitly_wait(10)
    driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(22)").click()
    htmlElement = driver.find_element(By.CSS_SELECTOR,"#form > div > div > div > h2")
    assert htmlElement.text == "ACCOUNT CREATED!"


'''
def test_testsignin(driver):
    driver.get("https://automationexercise.com/")
    driver.find_element(By.LINK_TEXT, "Signup / Login").click()
    driver.find_element(By.NAME, "email").click()
    driver.find_element(By.NAME, "email").send_keys("khaledblb@gmaill.com")
    driver.find_element(By.NAME, "password").send_keys("khaledd1")
    driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    # driver.find_element(By.LINK_TEXT, "Logout").click()
    driver.implicitly_wait(5)
    htmlElement = driver.find_element(By.CSS_SELECTOR, "#header > div > div > div > div.col-sm-8 > div > ul > li:nth-child(10) > a")
    assert htmlElement.text.find("logged in") == -1
'''
def random_char(y) :
    return ''.join(random.choice(string.ascii_letters) for x in range(y))